---
- name: Ping - Display IP Address of Azure Inventory Host Group
  hosts: "{{ tower_hostgroup_name }}"
  gather_facts: no

  tasks:
  - ping:
  - debug:
      msg: "{{ name }} IP Address is {{ public_ip }}"
...