---
- name: Provision Virtual Network
  hosts: localhost
  gather_facts: false

  vars:
    demo_rg_name: rg-aap-demo
    demo_vnet_state: present
    demo_vnet_list:
      - vnet_name: vnet-aap-demo-cli
        vnet_address_prefixes_cidr:
          - 172.16.132.0/23
        # vnet_dns_servers:
        #   - 168.63.129.16
      - vnet_name: vnet-aap-demo
        vnet_address_prefixes_cidr:
          - 172.16.134.0/23
        vnet_dns_servers:
          - 168.63.129.16
    demo_tags:
      demo: aap
      guid: zn56b

  tasks:
    - name: Process VNET List
      ansible.builtin.include_role:
        name: virtualnetwork
      vars:
        vnet_rg_name: "{{ demo_rg_name }}"
        vnet_name: "{{ item.vnet_name }}"
        vnet_address_prefixes_cidr: "{{ item.vnet_address_prefixes_cidr }}"
        vnet_dns_servers: "{{ item.vnet_dns_servers | default(omit) }}"
        vnet_state: "{{ demo_vnet_state }}"
        vnet_tags: "{{ demo_tags }}"
      loop: "{{ demo_vnet_list }}"

    - name: Create VNET Peering (A)
      azure.azcollection.azure_rm_virtualnetworkpeering:
        resource_group: "{{ demo_rg_name }}"
        virtual_network: vnet-aap-demo-cli
        name: vnet-aap-demo-cli-to-vnet-aap-demo
        remote_virtual_network:
          resource_group: "{{ demo_rg_name }}"
          name: vnet-aap-demo
        allow_virtual_network_access: true
        allow_forwarded_traffic: true

    - name: Create VNET Peering (B)
      azure.azcollection.azure_rm_virtualnetworkpeering:
        resource_group: "{{ demo_rg_name }}"
        virtual_network: vnet-aap-demo
        name: vnet-aap-demo-to-vnet-aap-demo-cli
        remote_virtual_network:
          resource_group: "{{ demo_rg_name }}"
          name: vnet-aap-demo-cli
        allow_virtual_network_access: true
        allow_forwarded_traffic: true
