---
- name: Provision Virtual Machine
  hosts: localhost
  gather_facts: false

  vars:
    demo_rg_name: rg-aap-demo
    demo_vm_list:
      # - { vm_name: aap-jumphost-cli, vnet_name: vnet-aap-demo-cli, subnet_name: snet-aap-demo-cli,
      #     vm_size: Standard_B4as_v2, vm_os_disk_size_gb: 64, vm_public_ip_name: aap-jumphost-cli-pip }
      - { vm_name: aap-jumphost, vnet_name: vnet-aap-demo, subnet_name: snet-aap-demo-jumphost,
          vm_size: Standard_B4ms, vm_os_disk_size_gb: 64, vm_public_ip_name: aap-jumphost-pip }
      # Single All-in-One AAP VM
      # - { vm_name: aap-demo, vnet_name: vnet-aap-demo, subnet_name: snet-aap-demo-app,
      #     vm_size: Standard_B4as_v2, vm_os_disk_size_gb: 120 }
      # Below are for Enterprise AAP VM
      - { vm_name: aap-gateway-host1, vnet_name: vnet-aap-demo, subnet_name: snet-aap-demo-fe,
          vm_size: Standard_D4s_v4, vm_os_disk_size_gb: 64, vm_public_ip_name: aap-gateway-host1-pip } # Standard_B4ms
      - { vm_name: aap-gateway-host2, vnet_name: vnet-aap-demo, subnet_name: snet-aap-demo-fe,
          vm_size: Standard_D4s_v4, vm_os_disk_size_gb: 64, vm_public_ip_name: aap-gateway-host2-pip }
      - { vm_name: aap-controller-host1, vnet_name: vnet-aap-demo, subnet_name: snet-aap-demo-app,
          vm_size: Standard_D4s_v5, vm_os_disk_size_gb: 64 } # Standard_B4s_v2
      - { vm_name: aap-controller-host2, vnet_name: vnet-aap-demo, subnet_name: snet-aap-demo-app,
          vm_size: Standard_D4s_v5, vm_os_disk_size_gb: 64 }
      - { vm_name: aap-eda-host1, vnet_name: vnet-aap-demo, subnet_name: snet-aap-demo-app,
          vm_size: Standard_D4as_v4, vm_os_disk_size_gb: 64 }
      - { vm_name: aap-eda-host2, vnet_name: vnet-aap-demo, subnet_name: snet-aap-demo-app,
          vm_size: Standard_D4as_v4, vm_os_disk_size_gb: 64 }
      - { vm_name: aap-hub-host1, vnet_name: vnet-aap-demo, subnet_name: snet-aap-demo-app,
          vm_size: Standard_D4as_v5, vm_os_disk_size_gb: 64 }
      - { vm_name: aap-hub-host2, vnet_name: vnet-aap-demo, subnet_name: snet-aap-demo-app,
          vm_size: Standard_D4as_v5, vm_os_disk_size_gb: 64 }
      - { vm_name: aap-execution-host1, vnet_name: vnet-aap-demo, subnet_name: snet-aap-demo-app,
          vm_size: Standard_D4ads_v5, vm_os_disk_size_gb: 64 }
      - { vm_name: aap-execution-host2, vnet_name: vnet-aap-demo, subnet_name: snet-aap-demo-app,
          vm_size: Standard_D4ads_v5, vm_os_disk_size_gb: 64 }
    demo_vm_state: present
    demo_vm_username: demoadmin
    demo_vm_password: changeme
    demo_vm_image:
      # use raw as lvm offer does not provide full root partition size
      offer: rhel-raw
      publisher: RedHat
      sku: '9_5'
      version: latest
    demo_tags:
      demo: aap
      guid: zn56b

  tasks:
    - name: Process VM List
      ansible.builtin.include_role:
        name: virtualmachine
      vars:
        subnet_rg_name: "{{ demo_rg_name }}"
        subnet_vnet_name: "{{ item.vnet_name }}"
        vm_rg_name: "{{ demo_rg_name }}"
        vm_name: "{{ item.vm_name }}"
        subnet_name: "{{ item.subnet_name }}"
        vm_state: "{{ demo_vm_state }}"
        vm_size: "{{ item.vm_size }}"
        vm_os_disk_size_gb: "{{ item.vm_os_disk_size_gb }}"
        vm_public_ip_name: "{{ item.vm_public_ip_name }}"
        vm_username: "{{ demo_vm_username }}"
        vm_password: "{{ demo_vm_password }}"
        vm_image: "{{ demo_vm_image }}"
        vm_tags: "{{ demo_tags }}"
      loop: "{{ demo_vm_list }}"
