---
- name: Provision Resource Group
  hosts: localhost
  gather_facts: false

  vars:
    demo_rg_name: rg-aap-demo
    demo_vnet_name: vnet-aap-demo
    demo_vm_name: vm-aap-demo-1
    demo_subnet_name: snet-aap-demo-1
    demo_vm_size: Standard_B1s
    dmeo_vm_os_disk_size_gb: 128
    demo_vm_state: present
    demo_vm_username: demoadmin
    demo_vm_password: changeme
    demo_tags:
      demo: aap
      guid: zn56b

  tasks:
    - name: Process VM List
      ansible.builtin.include_role:
        name: virtualmachine
      vars:
        subnet_rg_name: "{{ demo_rg_name }}"
        subnet_vnet_name: "{{ demo_vnet_name }}"
        vm_rg_name: "{{ demo_rg_name }}"
        vm_name: "{{ demo_vm_name }}"
        subnet_name: "{{ demo_subnet_name }}"
        vm_state: "{{ demo_vm_state }}"
        vm_size: "{{ demo_vm_size }}"
        vm_os_disk_size_gb: "{{ dmeo_vm_os_disk_size_gb }}"
        vm_username: "{{ demo_vm_username }}"
        vm_password: "{{ demo_vm_password }}"
        vm_tags: "{{ demo_tags }}"
