---
- name: Create Windows Server 2016 DC (B1S) VM on Azure 
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: Create virtual machine
    azure_rm_virtualmachine:
      resource_group: "{{ azure_group_name }}"
      name: "{{ azure_new_vm_name }}"
      short_hostname: "{{ azure_new_vm_name }}"
      vm_size: Standard_B1s
      admin_username: "{{ azure_windows_user }}"
      admin_password: "{{ azure_windows_password }}"
      started: yes
      os_type: Windows
      public_ip_allocation_method: Dynamic
      image:
        offer: WindowsServer
        publisher: MicrosoftWindowsServer
        sku: 2016-Datacenter
        version: latest
    delegate_to: localhost
...