---
- name: Update Security Port on 3Tier App Servers
  hosts: "{{ tower_hostgroup_name }}"
  gather_facts: no

  vars:
    - http_port: 80

  tasks:
  - name: display hostname
    debug: msg: "Hostname is {{ name }}"
    
  - name: Allow SSH and HTTP on rhproxy and rhtest
    azure_rm_securitygroup:
      resource_group: "{{ resource_group }}"
      name: "{{ security_group }}"
      rules:
        - name: Allow SSH
          protocol: TCP
          destination_port_range: 22
          access: Allow
          priority: 100
          direction: Inbound
        - name: Allow HTTP
          protocol: TCP
          destination_port_range: "{{ http_port }}"
          access: Allow
          priority: 102
          direction: Inbound
    when:
      - "'rhtest' in name"
      - "'rhproxy' in name"
    delegate_to: localhost

  - name: Allow SSH and SQL on rhsql
    azure_rm_securitygroup:
      resource_group: "{{ resource_group }}"
      name: "{{ security_group }}"
      rules:
        - name: Allow SSH
          protocol: TCP
          destination_port_range: 22
          access: Allow
          priority: 100
          direction: Inbound
        - name: Allow HTTP
          protocol: TCP
          source_address_prefix: '10.0.0.0/8'
          destination_port_range: 3306
          access: Allow
          priority: 102
          direction: Inbound
    when:
      - "'rhsql' in name"
    delegate_to: localhost
...