---
- name: Create RHEL VM on Azure
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - azure_vars.yml
    - vm_size: Standard_B1s
    - offer: UbuntuServer
    - publisher: Canonical
    - sku: 18.04-LTS
    - version: latest  

  tasks:
  - name: Create virtual machine
    azure_rm_virtualmachine:
      resource_group: "{{ azure_group_name }}"
      name: "{{ target_host_name }}"
      short_hostname: "{{ target_host_name }}"
      vm_size: "{{ vm_size }}"
      admin_username: "{{ azure_ssh_user }}"
      ssh_password_enabled: false
      ssh_public_keys:
      - path: "/home/{{ azure_ssh_user }}/.ssh/authorized_keys"
        key_data: "{{ azure_ssh_key }}"
      started: yes
      os_type: Linux
      public_ip_allocation_method: Dynamic     
      image:
        offer: "{{ offer }}"
        publisher: "{{ publisher }}"
        sku: "{{ sku }}"
        version: "{{ version }}"
    delegate_to: localhost
...