---
- name: Provision Resource Group
  hosts: localhost
  gather_facts: false

  vars:
    demo_rg_name: aap_demo_rg
    demo_vnet_name: aap_demo_vnet
    demo_vm_list:
      - { vm_name: aap-demo-vm1, subnet_name: aap_demo_subnet1, vm_size: Standard_B1s, vm_os_disk_size_gb: 64 }
      - { vm_name: aap-demo-vm2, subnet_name: aap_demo_subnet2, vm_size: Standard_B1s, vm_os_disk_size_gb: 64 }
      - { vm_name: aap-demo-vm3, subnet_name: aap_demo_subnet3, vm_size: Standard_B1s, vm_os_disk_size_gb: 64 }
    demo_vm_state: present
    vm_username: demoadmin
    vm_password: changeme
    demo_tags:
      demo: aap
      guid: zn56b

  tasks:
    - name: Process VM List
      ansible.builtin.include_role:
        name: virtualmachine
      vars:
        subnet_rg_name: "{{ demo_rg_name }}"
        subnet_vnet_name: "{{ demo_vnet_name }}"
        vm_rg_name: "{{ demo_rg_name }}"
        vm_name: "{{ item.vm_name }}"
        subnet_name: "{{ item.subnet_name }}"
        vm_state: "{{ demo_vm_state }}"
        vm_size: "{{ item.vm_size }}"
        vm_os_disk_size_gb: "{{ item.vm_os_disk_size_gb }}"
        vm_username: "{{ demo_vm_username }}"
        vm_password: "{{ demo_vm_password }}"
        vm_tags: "{{ demo_tags }}"
      loop: "{{ demo_vm_list }}"
