---
- name: Update Security Port on Windows Servers
  hosts: "{{ tower_hostgroup_name }}"
  gather_facts: no

  tasks:
  - name: Allow RDP and WinRM Inbound Ports
    azure_rm_securitygroup:
      resource_group: "{{ resource_group }}"
      name: "{{ security_group }}"
      rules:
        - name: RDP01
          protocol: Tcp
          source_address_prefix: "{{ tower_public_ip }}/32"
          destination_port_range: 3389
          access: Allow
          priority: 100
          direction: Inbound
        - name: WinRM01
          protocol: Tcp
          source_address_prefix: "{{ tower_public_ip }}/32"
          destination_port_range: 5986
          access: Allow
          priority: 101
          direction: Inbound           
    delegate_to: localhost
...