---
- name: Provision Resource Group
  hosts: localhost
  gather_facts: false

  vars:
    demo_rg_name: aap_demo_rg
    demo_rg_location: eastus
    demo_tags:
      demo: aap
      guid: zn56b

  roles:
    - role: resourcegroup
      vars:
        rg_name: "{{ demo_rg_name }}"
        rg_location: "{{ demo_rg_location }}"
        rg_tags: "{{ demo_tags }}"
