---
- name: Azure playbook to allocate and power on all VMs
  hosts: "{{ tower_hostgroup_name }}"
  connection: local
  gather_facts: no

  tasks:
  - name: allocate virtual machines
    azure_rm_virtualmachine:
      resource_group: "{{ azure_group_name }}"
      name: "{{ name }}"
      allocated: yes
    delegate_to: localhost

  - name: power on virtual machines
    azure_rm_virtualmachine:
      resource_group: "{{ azure_group_name }}"
      name: "{{ name }}"
      started: yes
    delegate_to: localhost  
...