---
- name: Provision Resource Group
  hosts: localhost
  gather_facts: false

  vars:
    demo_rg_name: rg-aap-demo
    demo_vm_list:
      - { vm_name: vm-aap-demo-1, vnet_name: vnet-aap-demo, subnet_name: snet-aap-demo-1, vm_size: Standard_B1s, vm_os_disk_size_gb: 128 }
      - { vm_name: vm-aap-demo-2, vnet_name: vnet-aap-demo, subnet_name: snet-aap-demo-2, vm_size: Standard_B1s, vm_os_disk_size_gb: 64 }
      - { vm_name: vm-aap-demo-cli, vnet_name: vnet-aap-demo-cli, subnet_name: snet-aap-demo-cli, vm_size: Standard_B1s, vm_os_disk_size_gb: 128 }
    demo_vm_state: present
    demo_vm_username: demoadmin
    demo_vm_password: changeme
    demo_tags:
      demo: aap
      guid: zn56b

  tasks:
    - name: Process VM List
      ansible.builtin.include_role:
        name: virtualmachine
      vars:
        subnet_rg_name: "{{ demo_rg_name }}"
        subnet_vnet_name: "{{ item.vnet_name }}"
        vm_rg_name: "{{ demo_rg_name }}"
        vm_name: "{{ item.vm_name }}"
        subnet_name: "{{ item.subnet_name }}"
        vm_state: "{{ demo_vm_state }}"
        vm_size: "{{ item.vm_size }}"
        vm_os_disk_size_gb: "{{ item.vm_os_disk_size_gb }}"
        vm_username: "{{ demo_vm_username }}"
        vm_password: "{{ demo_vm_password }}"
        vm_tags: "{{ demo_tags }}"
      loop: "{{ demo_vm_list }}"
