---
- name: Create default NSG - {{ subnet_name }}
  azure.azcollection.azure_rm_securitygroup:
    resource_group: "{{ subnet_rg_name }}"
    name: "nsg-{{ subnet_name }}"
    # not to remove rules not matching those defined in rules
    purge_rules: false
    rules:
      - name: Deny-Inbound
        description: Block all Inbound
        direction: Inbound
        priority: 4096
        protocol: "*"
        source_port_range: "*"
        source_address_prefix: "*"
        destination_port_range: "*"
        destination_address_prefix: "*"
        access: Deny
      - name: Deny-Outbound
        description: Block all Outbound
        direction: Outbound
        priority: 4096
        protocol: "*"
        source_port_range: "*"
        source_address_prefix: "*"
        destination_port_range: "*"
        destination_address_prefix: "*"
        access: Deny

- name: Ensure Subnet is Present - {{ subnet_name }}
  azure.azcollection.azure_rm_subnet:
    resource_group: "{{ subnet_rg_name }}"
    virtual_network_name: "{{ subnet_vnet_name }}"
    name: "{{ subnet_name }}"
    address_prefix_cidr: "{{ subnet_address_prefix_cidr }}"
    state: "{{ subnet_state }}"
    security_group: "nsg-{{ subnet_name }}"
