---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel9:latest

options:
  package_manager_path: /usr/bin/microdnf

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

# If specif ansible.cfg is needed
  additional_build_files:
    - src: files/ansible.cfg
      dest: configs

additional_build_steps:
  prepend_galaxy:
    - RUN pip3 install --upgrade pip setuptools
    - RUN whoami
    - RUN cat /etc/os-release
    # - COPY _build/configs/ansible.cfg /etc/ansible/ansible.cfg
  append_galaxy:
    - RUN echo Build done!
